Battery widget
sonia-auv/rqt_sonia_plugins pull request #19
Opened 2020-02-24 17:41 UTC by Kam0ss

## Description
Added a pop-up when one of the battery voltage is running low.
Changed battery appearance for a progressBar instead of a slider.
Changed batteries ui sizes

## Fixes
Link all the related issues from the issue tracker
- Closes: #15 #13 

## How has this been tested ?
(If possible) describe the steps to test these modifications.

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2020-03-03 21:25 UTC, gauthiermartin requested changes
Some changes are required

2020-03-03 21:25 UTC, gauthiermartin commented on rqt_toolbar/src/rqt_toolbar/ToolbarBatteryWidget.py
> +\modified by : Camille Sauvain
This header should be removed

2020-03-03 21:25 UTC, gauthiermartin commented on rqt_toolbar/src/rqt_toolbar/ToolbarBatteryWidget.py
> +            if msg.data <= float(self.bat_warning):
Why are we casting to float here ?

2020-03-03 21:25 UTC, gauthiermartin commented on rqt_toolbar/src/rqt_toolbar/ToolbarBatteryWidget.py
> +        if msg.data <= float(self.bat_warning) and self.nb_msg == 0 and self.nb == 5:
Why are we casting to float here

2020-03-03 21:25 UTC, gauthiermartin commented on rqt_toolbar/src/rqt_toolbar/ToolbarBatteryWidget.py
>              root = Tk()
We should consider using QTMessageBox https://www.tutorialspoint.com/pyqt/pyqt_qmessagebox.htm

2020-03-04 03:50 UTC, Kam0ss reviewed
Changes asked are done.

2020-03-04 12:31 UTC, gauthiermartin approved these changes
LGTM 👍

2020-03-04 18:16 UTC, merged